config/routes.rb
Rails.application.routes.draw do
  root to: 'shifts#index'
  devise_for :users
  resources :shifts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shift.rb
class Shift < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    @shift = Shift.all
  end

  def new
    @shift = Shift.new
  end

  def edit; end

  def create
    @shift = Shift.new(shift_params)
  end

  def udpate; end

  def destroy; end

  private

  def shift_params
    params.require(:shift).permit(:name, :day)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Myapp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shifts/_form.html.haml
= form_for @shift do |f|
  - if @shift.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shift.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @shift.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :name, '名前'
    = f.text_field :name
  .form-group
    = f.label :day, '希望日程'
    = f.text_field :day

app/views/shifts/index.html.haml
%h2 Hello

app/views/shifts/new.html.haml
.container
  .row
    .col-12
      = render 'form'
      %button
        = link_to 'Back', shifts_path, class: 'button-style'